[package]
name = "test_db"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rusqlite"
path = "src/rusqlite.rs"

[dependencies]
psutil = "5.2.0"
rusqlite = "0.34.0"
sqlite = { version = "0.36.2", default-features = false }
